<a href="https://colab.research.google.com/github/vani4vani/Bank_Note_Authentification/blob/pred-note/bank_note_auth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting if a note is genuine


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
df = pd.read_csv('data_banknote_authentication.txt', header=None, names=["variance_wti", "skewness_wti", "curtosis_wti", "entropy_i", "class"])
df.head()

variance_wti  skewness_wti  curtosis_wti  entropy_i  class
0       3.62160        8.6661       -2.8073   -0.44699      0
1       4.54590        8.1674       -2.4586   -1.46210      0
2       3.86600       -2.6383        1.9242    0.10645      0
3       3.45660        9.5228       -4.0112   -3.59440      0
4       0.32924       -4.4552        4.5718   -0.98880      0

In [27]:
df.shape

(1372, 5)

In [28]:
df.isnull().sum()

variance_wti    0
skewness_wti    0
curtosis_wti    0
entropy_i       0
class           0
dtype: int64

In [13]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [14]:
print(X)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [20]:
y = y.reshape(len(y), 1)


In [21]:
print(y)

[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [23]:
print(X_train)

[[ 2.9736    8.7944   -3.6359   -1.3754  ]
 [ 2.6648   10.754    -3.3994   -4.1685  ]
 [-3.7573   -8.2916   10.3032    0.38059 ]
 ...
 [ 0.6005    0.99945  -2.2126    0.097399]
 [ 2.0165   -0.25246   5.1707    1.0763  ]
 [-2.0759   10.8223    2.6439   -4.837   ]]


In [24]:
print(y_train)

[[0]
 [0]
 [1]
 ...
 [1]
 [0]
 [0]]


In [25]:
print(X_test)

[[ -1.7713   -10.7665    10.2184    -1.0043  ]
 [  5.1321    -0.031048   0.32616    1.1151  ]
 [ -2.0149     3.6874    -1.9385    -3.8918  ]
 ...
 [  1.3114     4.5462     2.2935     0.22541 ]
 [  3.5152     6.8224    -0.67377   -0.46898 ]
 [  5.7227     5.8312    -2.4097    -0.24527 ]]


In [26]:
print(y_test)

[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
print(X_train)

[[ 0.89967493  1.18805208 -1.18171152 -0.09274226]
 [ 0.79132601  1.52427784 -1.12635383 -1.42833711]
 [-1.4620017  -1.74354285  2.08102182  0.74693093]
 ...
 [ 0.06702331 -0.14939588 -0.84855885  0.61151564]
 [ 0.56385644 -0.36419707  0.87965453  1.07960312]
 [-0.87204745  1.53599667  0.28820496 -1.74799811]]


In [31]:
print(X_test)

[[-0.76517219 -2.16818315  2.06117264  0.08470905]
 [ 1.65702967 -0.32620747 -0.25430981  1.09815637]
 [-0.85064433  0.31179928 -0.78440011 -1.29602567]
 ...
 [ 0.3164574   0.45915113  0.20618663  0.6727275 ]
 [ 1.08970658  0.84969873 -0.48836401  0.3406865 ]
 [ 1.864254    0.67962985 -0.89469417  0.44765937]]


In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [34]:
print(classifier.predict(sc.transform([[3.62160, 8.6661, -2.8073,-0.44699]])))

[0]


In [35]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[190   5]
 [  2 146]]


0.9795918367346939